import pandas as pd
import numpy as np

# load the csv file to a pd dataframe
main = pd.read_csv('WikipediaEarthquakes1.csv')

# manual search of depth of each earthquake (from Wikipedia as well)
# the mean of the bounds of the interval was used for ranges (e.g. 4.5 km for 4-5 km)
depth_data_upto17th = np.array([np.nan, 
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                5.5,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                19.5,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                27.5,
                                np.nan,
                                18.5,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                np.nan,
                                30,
                                np.nan,
                                np.nan,
                                15,
                                np.nan,
                                15,
                                np.nan,
                                11,
                                np.nan,
                                12,
                                25,
                                np.nan,
                                40,
                                np.nan,
                                np.nan,
                                30,
                                10,
                                np.nan,
                                np.nan,
                                np.nan,
                                100
                                ])

depth_data_18th = np.array([np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            7.5,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            40,
                            30,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            15,
                            np.nan,
                            85,
                            10,
                            np.nan,
                            20,
                            np.nan,
                            20,
                            np.nan,
                            np.nan,
                            np.nan])

depth_data_19th = np.array([150,
                            90,
                            np.nan,
                            np.nan,
                            np.nan,
                            33,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            33,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            185,
                            np.nan,
                            np.nan,
                            33,
                            np.nan,
                            80.5,
                            10,
                            np.nan,
                            np.nan,
                            30,
                            np.nan,
                            np.nan,
                            80,
                            30,
                            10,
                            9,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            60,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            12,
                            np.nan,
                            10,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            34,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                            15
                            ])

# merge all datasets
depth_data = np.concatenate((depth_data_upto17th,depth_data_18th, depth_data_19th))

# check if locations match with added depths as it is done manually
'''
indices = np.where(depth_data > 0)[0]
indices = indices.tolist()
for i in indices:
    print(main.iloc[i])
'''

# add depth column to the dataframe
main['Depth'] = depth_data 

# print(main)

# export csv file
main.to_csv('WikipediaEarthquakes2.csv', index=False)